export type Track = {
  title: string;
  artist: string;
  album?: string;
  durationMs: number;
};

// Source: https://open.spotify.com/playlist/2H8XDLZ2YawlGYAdTWRmqe
export const TRACKS: Track[] = [
  { title: "One", artist: "Metallica", durationMs: 447000 },
  { title: "For Whom The Bell Tolls - Remastered", artist: "Metallica", durationMs: 309000 },
  { title: "Fade To Black - Remastered", artist: "Metallica", durationMs: 417000 },
  { title: "Seek & Destroy - Remastered", artist: "Metallica", durationMs: 414000 },
  { title: "Whiskey In The Jar", artist: "Metallica", durationMs: 304000 },
  { title: "Wherever I May Roam - Remastered 2021", artist: "Metallica", durationMs: 404000 },
  { title: "Sad But True", artist: "Metallica", durationMs: 323000 },
  { title: "Enter Sandman", artist: "Metallica", durationMs: 331000 },
  { title: "Wherever I May Roam", artist: "Metallica", durationMs: 403000 },
  { title: "The Unforgiven", artist: "Metallica", durationMs: 386000 },
  { title: "Nothing Else Matters", artist: "Metallica", durationMs: 388000 },
  { title: "Master Of Puppets", artist: "Metallica", durationMs: 515000 },
  { title: "The Unforgiven II", artist: "Metallica", durationMs: 396000 },
  { title: "Fuel", artist: "Metallica", durationMs: 269000 },
  { title: "The Unforgiven III", artist: "Metallica", durationMs: 466000 },
  { title: "For Whom the Bell Tolls - Live / Seattle '89", artist: "Metallica", durationMs: 330000 },
  { title: "November Rain", artist: "Guns N' Roses", durationMs: 536000 },
  { title: "Don't Cry (Original)", artist: "Guns N' Roses", durationMs: 283000 },
  { title: "Live And Let Die", artist: "Guns N' Roses", durationMs: 182000 },
  { title: "Knockin' On Heaven's Door", artist: "Guns N' Roses", durationMs: 336000 },
  { title: "Estranged", artist: "Guns N' Roses", durationMs: 563000 },
  { title: "You Could Be Mine", artist: "Guns N' Roses", durationMs: 343000 },
  { title: "Welcome To The Jungle", artist: "Guns N' Roses", durationMs: 273000 },
  { title: "Sweet Child O' Mine", artist: "Guns N' Roses", durationMs: 356000 },
  { title: "Paint It, Black", artist: "The Rolling Stones", durationMs: 202000 },
  { title: "Highway to Hell", artist: "AC/DC", durationMs: 208000 },
  { title: "Rock N Roll Train", artist: "AC/DC", durationMs: 260000 },
  { title: "Thunderstruck", artist: "AC/DC", durationMs: 292000 },
  { title: "T.N.T.", artist: "AC/DC", durationMs: 215000 },
  { title: "Back In Black", artist: "AC/DC", durationMs: 256000 },
  { title: "Chop Suey!", artist: "System Of A Down", durationMs: 210000 },
  { title: "Toxicity", artist: "System Of A Down", durationMs: 218000 },
  { title: "Aerials", artist: "System Of A Down", durationMs: 235000 },
  { title: "Jet Pilot", artist: "System Of A Down", durationMs: 126000 },
  { title: "Sugar", artist: "System Of A Down", durationMs: 153000 },
  { title: "Lonely Day", artist: "System Of A Down", durationMs: 167000 },
  { title: "Hypnotize", artist: "System Of A Down", durationMs: 189000 },
  { title: "B.Y.O.B.", artist: "System Of A Down", durationMs: 255000 },
  { title: "How You Remind Me", artist: "Nickelback", durationMs: 223000 },
  { title: "Everlong", artist: "Foo Fighters", durationMs: 250000 },
  { title: "My Hero", artist: "Foo Fighters", durationMs: 260000 },
  { title: "The Pretender", artist: "Foo Fighters", durationMs: 269000 },
  { title: "Bring Me To Life", artist: "Evanescence", durationMs: 235000 },
  { title: "My Immortal", artist: "Evanescence", durationMs: 262000 },
  { title: "Going Under", artist: "Evanescence", durationMs: 214000 },
  { title: "21 Guns", artist: "Green Day", durationMs: 321000 },
  { title: "Wake Me up When September Ends", artist: "Green Day", durationMs: 285000 },
  { title: "Boulevard of Broken Dreams", artist: "Green Day", durationMs: 262000 },
  { title: "Holiday", artist: "Green Day", durationMs: 247000 },
  { title: "American Idiot", artist: "Green Day", durationMs: 176000 },
  { title: "The Reason", artist: "Hoobastank", durationMs: 232000 },
  { title: "The Trooper - 2015 Remaster", artist: "Iron Maiden", durationMs: 252000 },
  { title: "Domination", artist: "Pantera", durationMs: 305000 },
  { title: "Holy Wars...The Punishment Due - 2004 Remix", artist: "Megadeth", durationMs: 392000 },
  { title: "Symphony Of Destruction - Remastered 2012", artist: "Megadeth", durationMs: 241000 },
  { title: "Given Up", artist: "Linkin Park", durationMs: 189000 },
  { title: "Faint", artist: "Linkin Park", durationMs: 162000 },
  { title: "Crawling", artist: "Linkin Park", durationMs: 208000 },
  { title: "Numb", artist: "Linkin Park", durationMs: 187000 },
  { title: "What I've Done", artist: "Linkin Park", durationMs: 205000 },
  { title: "By Myself", artist: "Linkin Park", durationMs: 189000 },
  { title: "In the End", artist: "Linkin Park", durationMs: 216000 },
  { title: "Somewhere I Belong", artist: "Linkin Park", durationMs: 213000 },
  { title: "Holiday / Boulevard of Broken Dreams", artist: "Green Day", durationMs: 493000 },
  { title: "Basket Case", artist: "Green Day", durationMs: 181000 },
  { title: "Paradise City", artist: "Guns N' Roses", durationMs: 405000 },
  { title: "Complicated", artist: "Avril Lavigne", durationMs: 244000 },
  { title: "My Happy Ending", artist: "Avril Lavigne", durationMs: 242000 },
  { title: "Sk8er Boi", artist: "Avril Lavigne", durationMs: 204000 },
  { title: "Girlfriend", artist: "Avril Lavigne", durationMs: 216000 },
  { title: "Still Loving You", artist: "Scorpions", durationMs: 387000 },
  { title: "Rock You Like A Hurricane", artist: "Scorpions", durationMs: 252000 },
  { title: "Wind Of Change", artist: "Scorpions", durationMs: 312000 },
  { title: "We Will Rock You - 2020 Remaster", artist: "Nickelback", durationMs: 120000 },
  { title: "Eye of the Tiger - 2006 Master", artist: "Survivor", durationMs: 255000 },
  { title: "Zombie", artist: "The Cranberries", durationMs: 306000 },
  { title: "Linger", artist: "The Cranberries", durationMs: 274000 },
  { title: "Smells Like Teen Spirit - Live At The Paramount", artist: "Nirvana", durationMs: 285000 },
  { title: "Smells Like Teen Spirit", artist: "Nirvana", durationMs: 301000 },
  { title: "Something In The Way", artist: "Nirvana", durationMs: 232000 },
  { title: "Heart-Shaped Box", artist: "Nirvana", durationMs: 281000 },
  { title: "The Man Who Sold The World - Live", artist: "Nirvana", durationMs: 261000 },
  { title: "Livin' On A Prayer", artist: "Bon Jovi", durationMs: 249000 },
  { title: "Born To Be My Baby", artist: "Bon Jovi", durationMs: 280000 },
  { title: "You Give Love A Bad Name", artist: "Bon Jovi", durationMs: 222000 },
  { title: "It's My Life", artist: "Bon Jovi", durationMs: 224000 },
  { title: "Como Yo Nadie Te Ha Amado", artist: "Bon Jovi", durationMs: 307000 },
  { title: "Always", artist: "Bon Jovi", durationMs: 353000 },
  { title: "I'll Be There For You", artist: "Bon Jovi", durationMs: 346000 },
  { title: "Bed Of Roses", artist: "Bon Jovi", durationMs: 394000 },
  { title: "This Ain't A Love Song", artist: "Bon Jovi", durationMs: 306000 },
  { title: "Bohemian Rhapsody", artist: "Queen", durationMs: 354000 },
  { title: "Killer Queen", artist: "Queen", durationMs: 179000 },
  { title: "Another One Bites The Dust", artist: "Queen", durationMs: 214000 },
  { title: "Don't Stop Me Now - Remastered 2011", artist: "Queen", durationMs: 209000 },
  { title: "I Want To Break Free", artist: "Queen", durationMs: 223000 },
  { title: "Eye of the Tiger", artist: "Survivor", durationMs: 245000 },
];
